baseURL = "BASE URL"
languageCode = "en-us"
googleAnalyticsID = "GOOGLE ANALYTICS ID"
theme = ["dark-blueberry"]

CanonifyUrls = true
BuildDrafts = false
PaginatePath = "p"
Paginate = 8
DisablePathToLower = false
HasCJKLanguage = true
PreserveTaxonomyNames = false
UglyUrls = false
PygmentsStyle = "solarized-dark256"
pygmentsCodefences = true

pygmentsCodefencesGuessSyntax = true

[Params]
  DateFormat = "2006-01-02"
  YearFormat = "2006"
  MonthFormat = "01-02"
  Fancybox = true

  codePenUser = "codepenuser name"

  AuthorImg = "/img/avatar.png"
  ImgLogo = "/img/logo.png"

  author = "AUTHOR NAME"
  introduce = "Basic Introduction"
  description = "Describe your website"

  disqusShortname = "DISQUS SHORTNAME"

  title = "TITLE"
  subtitle = "SUBTITLE"

  logoText = "LOGO TEXT"
  logoHomeLink = "/post"

[[Menu.Main]]
  Name = "Front Page"
  Pre = "home"
  URL = "/"
  Weight = 1
[[Menu.Main]]
  Name = "All Posts"
  Pre = "archive"
  URL = "/post/"
  Weight = 2
[[Menu.Main]]
  Name = "About"
  Pre = "user"
  URL = "/about/"
  Weight = 3
[[Menu.Main]]
  Name = "Notes"
  Pre = "book"
  URL = "/tags/school-notes/"
  Weight = 4
[[Menu.Main]]
  Name = "Contact"
  Pre = "phone"
  URL = "/contact"
  Weight = 7
[[Menu.Main]]
  Name = "Tags"
  Pre = "tags"
  URL = "/tags"
  Weight = 8

[markup.goldmark.renderer]
  unsafe = true

[[Params.Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "URL"

[[Params.Socials]]
  Name = "Reddit"
  Icon = "reddit"
  URL = "URL"  

[[Params.Socials]]
  Name = "Stack Overflow"
  Icon = "stack-overflow"
  URL = "URL"

[[Params.Socials]]
  Name = "Quora"
  Icon = "quora"
  URL = "URL"  

